REACT_APP_CONTACTFORMAPI=https://equiprents.herokuapp.com/api/public/contactus
REACT_APP_SIGNUPAPI=https://equiprents.herokuapp.com/api/public/signup
REACT_APP_SIGNINAPI=https://equiprents.herokuapp.com/api/public/signin

REACT_APP_SSSREQUEST=https://equiprents.herokuapp.com/api/admin/uploadUrl
REACT_APP_PRODUCTCREATEAPI=https://equiprents.herokuapp.com/api/admin/productCreate

REACT_APP_PRODUCTGETALL=https://equiprents.herokuapp.com/api/admin/productGetAll
REACT_APP_PRODUCTGETONE=https://equiprents.herokuapp.com/api/admin/productGet
REACT_APP_PRODUCTUPDATE=https://equiprents.herokuapp.com/api/admin/productPut
REACT_APP_PRODUCTSEARCHCATEGORY=https://equiprents.herokuapp.com/api/admin/categorysearch

REACT_APP_GETALLMSG=https://equiprents.herokuapp.com/api/admin/allmsg
REACT_APP_GETONEMSG=https://equiprents.herokuapp.com/api/admin/msg

REACT_APP_MAILSEND=https://equiprents.herokuapp.com/api/admin/msg/replyEmail

REACT_APP_STOREGETALL=https://equiprents.herokuapp.com/api/public/storeGetall
REACT_APP_STOREGETPRODUCTONE=https://equiprents.herokuapp.com/api/public/productGet
REACT_APP_SECTIONGETDATA=https://equiprents.herokuapp.com/api/public/sectionData
REACT_APP_CATEGORYGETDATA=https://equiprents.herokuapp.com/api/public/categoryData

REACT_APP_ORDERCREATE=https://equiprents.herokuapp.com/api/public/payment/orderCreate
REACT_APP_PAYMENTVERIFY=https://equiprents.herokuapp.com/api/public/payment/verifyPayment

REACT_APP_GETPROFILE=https://equiprents.herokuapp.com/api/private/Getprofile
REACT_APP_GETORDERS=https://equiprents.herokuapp.com/api/private/GetOrders

REACT_APP_GETALLORDERS=https://equiprents.herokuapp.com/api/admin/allOrders
